---
apic:
  tenants:
    - name: Tenant
    - name: test
    - name: test2
    - name: "!vault |\n          $ANSIBLE_VAULT;1.1;AES256\n          38373132393531386364386666323037666135303332623962613263663132656236303436633261\n\
        \          3136313734396334313233316131636566613339373934340a396562626262303238313538313566\n\
        \          37303233313330663465316232373430376166376664346239666331323965356332336630376133\n\
        \          6362646464373338390a313332303635303864626166333134396266643164373564646135653563\n\
        \          3166"
